### ISSUE TITLE
DB初始化出错

### ISSUE THREAD

**Issue by l0n3rs** [go-admin-team/go-admin#393]
按照官方文档一步一步走的
到DB初始化的时候，用go-admin那段命令行生成爆如下错误

```
M:\Gostudy\goadmin\go-admin>go-admin migrate -c=config/settings.dev.yml
start init
 2021-04-10T23:39:05.233+0800  file: database/initialize.go:31 level: info * => ?[0;0;32mroot:123456@tcp(127.0.0.1:3306)/goadmin?charset=utf8&par
seTime=True&loc=Local&timeout=1000ms?[0m
 2021-04-10T23:39:05.258+0800  file: gorm@v1.21.3/callbacks.go:206 level: info M:/GOPATH/pkg/mod/gorm.io/driver/mysql@v1.0.4-0.20201206014609-ae5
fd10184f6/mysql.go:54
[info] replacing callback `gorm:update` from M:/GOPATH/pkg/mod/gorm.io/driver/mysql@v1.0.4-0.20201206014609-ae5fd10184f6/mysql.go:54

 2021-04-10T23:39:05.270+0800  file: gorm@v1.21.3/callbacks.go:206 level: info M:/GOPATH/pkg/mod/gorm.io/driver/mysql@v1.0.4-0.20201206014609-ae5
fd10184f6/mysql.go:54
[info] replacing callback `gorm:update` from M:/GOPATH/pkg/mod/gorm.io/driver/mysql@v1.0.4-0.20201206014609-ae5fd10184f6/mysql.go:54

 2021-04-10T23:39:05.272+0800  file: database/initialize.go:58 level: info ?[0;0;32mmysql connect success !?[0m
 2021-04-10T23:39:05.273+0800  file: gorm@v1.21.3/callbacks.go:122 level: trace M:/GOPATH/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1
-0.20210310135230-1608cc35b95b/adapter.go:313  [0.000ms] [rows:-] SELECT DATABASE()
 2021-04-10T23:39:05.273+0800  file: gorm@v1.21.3/callbacks.go:122 level: trace M:/GOPATH/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1
-0.20210310135230-1608cc35b95b/adapter.go:313  [0.504ms] [rows:-] SELECT count(*) FROM information_schema.tables WHERE table_schema = 'goadmin' A
ND table_name = 'sys_casbin_rule' AND table_type = 'BASE TABLE'
 2021-04-10T23:39:05.333+0800  file: gorm@v1.21.3/callbacks.go:122 level: trace M:/GOPATH/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1
-0.20210310135230-1608cc35b95b/adapter.go:313  [59.350ms] [rows:0] CREATE TABLE `sys_casbin_rule` (`p_type` varchar(100),`v0` varchar(100),`v1` v
archar(100),`v2` varchar(100),`v3` varchar(100),`v4` varchar(100),`v5` varchar(100))
 2021-04-10T23:39:05.333+0800  file: gorm@v1.21.3/callbacks.go:122 level: trace M:/GOPATH/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1
-0.20210310135230-1608cc35b95b/adapter.go:319  [0.000ms] [rows:-] SELECT DATABASE()
 2021-04-10T23:39:05.334+0800  file: gorm@v1.21.3/callbacks.go:122 level: trace M:/GOPATH/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1
-0.20210310135230-1608cc35b95b/adapter.go:319  [0.713ms] [rows:-] SELECT count(*) FROM information_schema.statistics WHERE table_schema = 'goadmi
n' AND table_name = 'sys_casbin_rule' AND index_name = 'idx_sys_casbin_rule'
 2021-04-10T23:39:05.335+0800  file: gorm@v1.21.3/callbacks.go:122 level: trace M:/GOPATH/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1
-0.20210310135230-1608cc35b95b/adapter.go:321 Error 1071: Specified key was too long; max key length is 1000 bytes  [0.504ms] [rows:0] CREATE UNI
QUE INDEX idx_sys_casbin_rule ON sys_casbin_rule (p_type,v0,v1,v2,v3,v4,v5)
panic: Error 1071: Specified key was too long; max key length is 1000 bytes

goroutine 1 [running]:
github.com/go-admin-team/go-admin-core/sdk/pkg/casbin.Setup(0xc0002e2090, 0x3089dda, 0x4, 0x1)
        M:/GOPATH/pkg/mod/github.com/go-admin-team/go-admin-core@v1.3.4/sdk/pkg/casbin/mycasbin.go:30 +0x233
go-admin/common/database.setupSimpleDatabase(0x31f6fba, 0x1, 0xc0003f1140)
        M:/Gostudy/goadmin/go-admin/common/database/initialize.go:61 +0x9cb
go-admin/common/database.Setup()
        M:/Gostudy/goadmin/go-admin/common/database/initialize.go:23 +0xd9
go-admin/cmd/migrate.initDB(0xc0003f0e40, 0x3237c20)
        M:/Gostudy/goadmin/go-admin/cmd/migrate/server.go:86 +0x2d
go-admin/cmd/migrate.run()
        M:/Gostudy/goadmin/go-admin/cmd/migrate/server.go:60 +0x1ed
go-admin/cmd/migrate.glob..func1(0x2e1bc80, 0xc0008b2100, 0x0, 0x1)
        M:/Gostudy/goadmin/go-admin/cmd/migrate/server.go:34 +0x27
github.com/spf13/cobra.(*Command).execute(0x2e1bc80, 0xc0008b20e0, 0x1, 0x1, 0x2e1bc80, 0xc0008b20e0)
        M:/GOPATH/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2e1b4a0, 0x19e8c80, 0x0, 0x1)
        M:/GOPATH/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        M:/GOPATH/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
go-admin/cmd.Execute()
        M:/Gostudy/goadmin/go-admin/cmd/cobra.go:52 +0x34
main.main()
        M:/Gostudy/goadmin/go-admin/main.go:20 +0x27
```

**Comment by hsluoyz** [comment]
@closetool

**Comment by closetool** [comment]
@l0n3rs 可以试一下在go.mod文件里修改gorm版本吗, 把1.21.x改成1.20.x
因为gorm新版本bug很多

**Comment by y449329998** [comment]
数据库引擎设置为InnoDB就可以了
