### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by l0n3rs** [go-admin-team/go-admin#407]
![image](https://user-images.githubusercontent.com/31120718/116969999-c8bb2f00-ace9-11eb-899a-35c197cc812a.png)
```
2021-05-04T14:56:07.158+0800  file: gorm@v1.21.6/callbacks.go:127 level: trace M:/GOPATH/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1-0.202103101352
30-1608cc35b95b/adapter.go:362  [0.000ms] [rows:1] SELECT * FROM `sys_casbin_rule`
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x135769d]

goroutine 1 [running]:
github.com/go-admin-team/go-admin-core/sdk/config.Queue.Setup(0x0, 0x0, 0xc000310000, 0x31eb6f8, 0xc000310000, 0x0)
        M:/GOPATH/pkg/mod/github.com/go-admin-team/go-admin-core/sdk@v1.3.5-rc.0/config/queue.go:47 +0x1fd
go-admin/cmd/api.setup()
        M:/goadmin/go-admin/cmd/api/server.go:79 +0x269
```

**Comment by l0n3rs** [comment]
已解决，刚刚在群里看了下聊天记录找到了解决方案
在配置文件中添加一下如下内容即可
![image](https://user-images.githubusercontent.com/31120718/116971776-a545b380-acec-11eb-97c0-f5ea0e4fccb8.png)
不需要修改gorm版本
