### ISSUE TITLE
数据库初始化出错

### ISSUE THREAD

**Issue by safejob** [go-admin-team/go-admin#421]
mysql 5.7

go-admin.exe migrate -c=config/settings.yml
start init
 2021-05-14T18:09:48.586+0800  file: database/initialize.go:31 level: info * => [0;0;32mroot:root@tcp(127.0.0.1:3306)/go-admin?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
 2021-05-14T18:09:48.609+0800  file: gorm@v1.21.6/callbacks.go:211 level: info D:/golang/pkg/mod/gorm.io/driver/mysql@v1.0.4-0.20201206014609-ae5fd10184f6/mysql.go:54
[info] replacing callback `gorm:update` from D:/golang/pkg/mod/gorm.io/driver/mysql@v1.0.4-0.20201206014609-ae5fd10184f6/mysql.go:54

 2021-05-14T18:09:48.613+0800  file: database/initialize.go:58 level: info [0;0;32mmysql connect success !
 2021-05-14T18:09:48.614+0800  file: gorm@v1.21.6/callbacks.go:127 level: trace D:/golang/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1-0.20210310135230-1608cc35b95b/adapter.go:313  [0.998ms] [rows:-] SELECT DATABASE()
 2021-05-14T18:09:48.615+0800  file: gorm@v1.21.6/callbacks.go:127 level: trace D:/golang/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1-0.20210310135230-1608cc35b95b/adapter.go:313  [1.001ms] [rows:-] SELECT count(*) FROM information_schema.tables WHERE table_schema = 'go-admin' AND table_name = 'sys_casbin_rule' AND table_type = 'BASE TABLE'
 2021-05-14T18:09:48.615+0800  file: gorm@v1.21.6/callbacks.go:127 level: trace D:/golang/pkg/mod/gorm.io/driver/mysql@v1.0.4-0.20201206014609-ae5fd10184f6/migrator.go:196  [0.000ms] [rows:-] SELECT DATABASE()
 2021-05-14T18:09:48.617+0800  file: gorm@v1.21.6/callbacks.go:127 level: trace D:/golang/pkg/mod/gorm.io/driver/mysql@v1.0.4-0.20201206014609-ae5fd10184f6/migrator.go:205  [2.036ms] [rows:-] SELECT column_name, is_nullable, data_type, character_maximum_length, numeric_precision, numeric_scale , datetime_precision FROM information_schema.columns WHERE table_schema = 'go-admin' AND table_name = 'sys_casbin_rule'
 2021-05-14T18:09:48.618+0800  file: gorm@v1.21.6/callbacks.go:127 level: trace D:/golang/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1-0.20210310135230-1608cc35b95b/adapter.go:319  [0.000ms] [rows:-] SELECT DATABASE()
 2021-05-14T18:09:48.619+0800  file: gorm@v1.21.6/callbacks.go:127 level: trace D:/golang/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1-0.20210310135230-1608cc35b95b/adapter.go:319  [0.000ms] [rows:-] SELECT count(*) FROM information_schema.statistics WHERE table_schema = 'go-admin' AND table_name = 'sys_casbin_rule' AND index_name = 'idx_sys_casbin_rule'
 2021-05-14T18:09:48.619+0800  file: gorm@v1.21.6/callbacks.go:127 level: trace D:/golang/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1-0.20210310135230-1608cc35b95b/adapter.go:321 Error 1071: Specified key was too long; max key length is 1000 bytes  [0.000ms] [rows:0] CREATE UNIQUE INDEX idx_sys_casbin_rule ON sys_casbin_rule (p_type,v0,v1,v2,v3,v4,v5)
panic: Error 1071: Specified key was too long; max key length is 1000 bytes

goroutine 1 [running]:
github.com/go-admin-team/go-admin-core/sdk/pkg/casbin.Setup(0xc000766000, 0x2a44c18, 0x4, 0x1)
	D:/golang/pkg/mod/github.com/go-admin-team/go-admin-core/sdk@v1.3.5-rc.1/pkg/casbin/mycasbin.go:30 +0x213
go-admin/common/database.setupSimpleDatabase(0x2a432c1, 0x1, 0xc000367140)
	D:/golang-mod/go-admin-team/go-admin-1.3.5/common/database/initialize.go:61 +0xa0b
go-admin/common/database.Setup()
	D:/golang-mod/go-admin-team/go-admin-1.3.5/common/database/initialize.go:23 +0xd9
go-admin/cmd/migrate.initDB(0xc000384360, 0x2d43a60)
	D:/golang-mod/go-admin-team/go-admin-1.3.5/cmd/migrate/server.go:86 +0x2d
go-admin/cmd/migrate.run()
	D:/golang-mod/go-admin-team/go-admin-1.3.5/cmd/migrate/server.go:60 +0x1ed
go-admin/cmd/migrate.glob..func1(0x27abd60, 0xc001784810, 0x0, 0x1)
	D:/golang-mod/go-admin-team/go-admin-1.3.5/cmd/migrate/server.go:34 +0x27
github.com/spf13/cobra.(*Command).execute(0x27abd60, 0xc001784800, 0x1, 0x1, 0x27abd60, 0xc001784800)
	D:/golang/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x27ab580, 0x0, 0x0, 0x1)
	D:/golang/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	D:/golang/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
go-admin/cmd.Execute()
	D:/golang-mod/go-admin-team/go-admin-1.3.5/cmd/cobra.go:52 +0x34
main.main()
	D:/golang-mod/go-admin-team/go-admin-1.3.5/main.go:20 +0x27

**Comment by safejob** [comment]
默认表引擎为 MyISAM时会报错  更换为 InnoDB 解决
