### ISSUE TITLE
前台代码运行不起来

### ISSUE THREAD

**Issue by careylipu** [go-admin-team/go-admin#651]
大佬看看怎么回事，nodejs一堆错误运行不起来。王德法，
环境：
$ node --version
v14.19.3
$ npm -v
6.14.17

报错：
 INFO  Starting development server...
10% building 2/2 modules 0 activeevents.js:377
      throw er; // Unhandled 'error' event

    at FSReqCallback.oncomplete (fs.js:193:5)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/home/coder/project/goadmin/go-admin-ui/node_modules/webpack-dev-server/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/home/coder/project/goadmin/go-admin-ui/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:40:5)
    at setFsWatchListener (/home/coder/project/goadmin/go-admin-ui/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    [... lines matching original stack trace ...]
    at FSReqCallback.oncomplete (fs.js:193:5) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/coder/project/goadmin/go-admin-ui/public',
  filename: '/home/coder/project/goadmin/go-admin-ui/public'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! go-admin@2.0.6 dev: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the go-admin@2.0.6 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/coder/.npm/_logs/2022-05-31T13_23_09_676Z-debug.log

**Comment by wenjianzhang** [comment]
go-admin-ui的问题请在对应的项目中提交，谢谢
