### ISSUE TITLE
master分支初使化mysql数据库失败

### ISSUE THREAD

**Issue by haimait** [go-admin-team/go-admin#654]
master分支初使化mysql数据库失败
数据库版本5.7.31
下面是报错信息

$ go run main.go migrate -c config/settings.dev.yml 
start init
2022-06-03 02:01:50.400+0800 file:database/initialize.go:31 level:info * => root:123456@tcp(127.0.0.1:3306)/go_admin?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
2022-06-03 02:01:50.410+0800 file:gorm@v1.21.11/callbacks.go:223 level:info D:/code/go/pkg/mod/gorm.io/driver/mysql@v1.0.4-0.20201206014609-ae5fd10184f6/mysql.go:54 [info] replacing callback `gorm:update` from D:/c
ode/go/pkg/mod/gorm.io/driver/mysql@v1.0.4-0.20201206014609-ae5fd10184f6/mysql.go:54

2022-06-03 02:01:50.417+0800 file:database/initialize.go:58 level:info mysql connect success !
2022-06-03 02:01:50.420+0800 file:gorm@v1.21.11/callbacks.go:133 level:trace D:/code/go/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1-0.20210902112335-4148cb356a24/adapter.go:314 [2.504ms] [rows:-]
 SELECT DATABASE()
2022-06-03 02:01:50.424+0800 file:gorm@v1.21.11/callbacks.go:133 level:trace D:/code/go/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1-0.20210902112335-4148cb356a24/adapter.go:314 [3.122ms] [rows:-]
 SELECT count(*) FROM information_schema.tables WHERE table_schema = 'go_admin' AND table_name = 'sys_casbin_rule' AND table_type = 'BASE TABLE'
2022-06-03 02:01:50.441+0800 file:gorm@v1.21.11/callbacks.go:133 level:trace D:/code/go/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1-0.20210902112335-4148cb356a24/adapter.go:314 [16.465ms] [rows:0][0[13;201H
m CREATE TABLE `sys_casbin_rule` (`p_type` varchar(100),`v0` varchar(100),`v1` varchar(100),`v2` varchar(100),`v3` varchar(100),`v4` varchar(100),`v5` varchar(100))
2022-06-03 02:01:50.441+0800 file:gorm@v1.21.11/callbacks.go:133 level:trace D:/code/go/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1-0.20210902112335-4148cb356a24/adapter.go:320 [0.000ms] [rows:-]
 SELECT DATABASE()
2022-06-03 02:01:50.442+0800 file:gorm@v1.21.11/callbacks.go:133 level:trace D:/code/go/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1-0.20210902112335-4148cb356a24/adapter.go:320 [0.618ms] [rows:-]
 SELECT count(*) FROM information_schema.statistics WHERE table_schema = 'go_admin' AND table_name = 'sys_casbin_rule' AND index_name = 'idx_sys_casbin_rule'
2022-06-03 02:01:50.444+0800 file:gorm@v1.21.11/callbacks.go:133 level:trace D:/code/go/pkg/mod/github.com/go-admin-team/gorm-adapter/v3@v3.2.1-0.20210902112335-4148cb356a24/adapter.go:322 Error 1071: Specified key was
 too long; max key length is 1000 bytes [2.024ms] [rows:0] CREATE UNIQUE INDEX idx_sys_casbin_rule ON sys_casbin_rule (p_type,v0,v1,v2,v3,v4,v5)
panic: Error 1071: Specified key was too long; max key length is 1000 bytes

goroutine 1 [running]:
github.com/go-admin-team/go-admin-core/sdk/pkg/casbin.Setup(0xc00039f050?, {0x24?, 0xc00013efa0?})
        D:/code/go/pkg/mod/github.com/go-admin-team/go-admin-core/sdk@v1.3.9/pkg/casbin/mycasbin.go:30 +0x174
go-admin/common/database.setupSimpleDatabase({0x188ccd3, 0x1}, 0xc00012d380)
        D:/code/go/src/go-admin/go-admin/common/database/initialize.go:61 +0xbaf
go-admin/common/database.Setup(...)
        D:/code/go/src/go-admin/go-admin/common/database/initialize.go:23
        D:/code/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x34a2de0)
        D:/code/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
        D:/code/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
go-admin/cmd.Execute()
        D:/code/go/src/go-admin/go-admin/cmd/cobra.go:54 +0x25
main.main()
        D:/code/go/src/go-admin/go-admin/main.go:20 

![Uploading image.png…]()

**Comment by haimait** [comment]
ERROR 1071 (42000): Specified key was too long; max key length is 1000 bytes
错误原因：
mysql的存储引擎是myisam，需要修改存储引擎。
mysql 在创建单列索引的时候对列的长度是有限制的 myisam和innodb存储引擎下长度限制分别为1000 bytes和767 bytes。
解决方案：
vim /etc/my.cnf
 
```yml
# 在[mysqld] 下面添加MySQL默认的引擎设置
default-storage-engine=InnoDB
```

service mysqld restart
